# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a70de1344021eb143a24f7b5f0b07477a0066987ce6132e0fbbb26f201daa1ccb7280ba315a2a176be8df9c80ee5ed9025c3c8857578ca85921f67831a0575c

test:
  secret_key_base: b8da8af3954e1952bc29bf7b822d4aa30822b5efb536f7296c427122c909cd90768e24f144ebfb6ac90718a3e671311df51a7bcfdce0a51b2c02114681203f05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
