# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cad6af4f1d73fccb9bce4a68c11e5e58b995047ed51c73582a52f994012fe7df1c3bc8d3d5e9eb73cf44236a85255271b5941f4a1056f9d58a67a19167d6685

test:
  secret_key_base: 8dbc817c1f8bb03c1979d513d06f3943bbebc2379476fdda7934dd1befe9e8b7c3361431a113e4a35034264169e9303bab3451d2d422f0814a4b6cf6d0a6dccc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
